default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: spotifysearch
  username: talon
  password: ....
  host: localhost
  encoding: utf8
  port: 5432

development:
  <<: *default
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: spotifysearch
  username: talon
  password: ....
  host: localhost
  encoding: utf8
  port: 5432


test:
  <<: *default
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: spotifysearch
  username: talon
  password: ....
  host: localhost
  encoding: utf8
  port: 5432

production:
  <<: *default
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: ...
  username: .....
  password: ....
  host: localhost
  encoding: utf8
  port: 5432
